## 1. Arrays & Basics (Creation, Shapes, Indexing, Slicing)

## Basic

In [4]:
# Problem 1: Create a 1D, 2D, and 3D NumPy array. Print the arrays and their shapes

In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [7]:
b=np.array([[1,2,3,4],[6,5,4,3]])
print(b)
print(b.shape)

[[1 2 3 4]
 [6 5 4 3]]
(2, 4)


In [8]:
c=np.array([
    [[1,2,3,4],[6,5,4,3]],
    [[1,2,3,4],[6,5,4,3]]
           
])
print(c)
print(c.shape)

[[[1 2 3 4]
  [6 5 4 3]]

 [[1 2 3 4]
  [6 5 4 3]]]
(2, 2, 4)


In [9]:
#•	Create an array of numbers from 0 to 20 with step size 2.

In [10]:
a=np.arange(0,21,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [11]:
#•	Slice the above array to get only even numbers.

In [12]:
a=np.arange(0,21)
print(a[::2])

[ 0  2  4  6  8 10 12 14 16 18 20]


In [13]:
#•	Create a 3x3 matrix and extract the 2nd row and 3rd column.

In [14]:
c = np.array([
    [1, 2, 3], 
    [6, 5, 4], 
    [1, 2, 3]
])

print(c.shape)

print("2nd row:", c[1, :])
print("3rd cols:", c[:,2])




(3, 3)
2nd row: [6 5 4]
3rd cols: [3 4 3]


## Intermediate!

In [33]:
#•	Create a 5x5 identity matrix.

In [53]:
a=np.identity(5)
print(a)
print(a.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


In [55]:
#•	Reshape an array of 25 numbers into a 5x5 matrix.

In [63]:
a=np.arange(25).reshape(5,5)
print(a)
print(a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [65]:
#•	Reverse an array without using loops.

In [67]:
a=np.array([1,4,2,3,4,5])
print(a[::-1])

[5 4 3 2 4 1]


## Advanced!

In [70]:
#•	Given a 6x6 matrix, extract the inner 4x4 submatrix

In [78]:
a=np.arange(36).reshape(6,6)
print(a)
print(a.shape)
inner = a[1:5, 1:5]
print( inner)
print( inner.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
(6, 6)
[[ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]
(4, 4)


In [80]:
#•	Write code to flatten any n-dimensional array into 1D.

In [84]:
a=np.arange(9).reshape(3,3)
print(a)
print(a.shape)
b=a.flatten()
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
[0 1 2 3 4 5 6 7 8]


## 2. Array Operations (Math, Broadcasting, Aggregations)

## Basic

In [ ]:
#• Perform element-wise addition, subtraction, multiplication, division on two arrays.

In [89]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a)
print(b)

print("Add", a + b)          
print("Sub", a - b)        
print("Multi", a * b)     
print("Divi", a / b)           

[1 2 3 4]
[5 6 7 8]
Add [ 6  8 10 12]
Sub [-4 -4 -4 -4]
Multi [ 5 12 21 32]
Divi [0.2        0.33333333 0.42857143 0.5       ]


In [91]:
#•	Calculate mean, median, variance, and standard deviation of an array.

In [93]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a)

print("mean:", np.mean(a))          
print("med", np.median(a))      
print("var", np.var(a))       
print("std dev", np.std(a))  


[1 2 3 4 5 6 7 8 9]
mean: 5.0
med 5.0
var 6.666666666666667
std dev 2.581988897471611


## Intermediate

In [98]:
# •	Given two arrays of shapes (3,1) and (1,3), perform broadcasting addition.

In [108]:
a = np.array([[1], 
              [2], 
              [3]])   

b = np.array([[10, 20, 30]])  

print("a shape:", a.shape)
print("b shape:", b.shape)

c = a + b

print("broadcasting addition:")
print(c)
print("Shape of result:", c.shape)


a shape: (3, 1)
b shape: (1, 3)
broadcasting addition:
[[11 21 31]
 [12 22 32]
 [13 23 33]]
Shape of result: (3, 3)


In [ ]:
# •	Normalize an array (scale values between 0 and 1).

In [110]:
arr = np.array([10, 20, 30, 40, 50])

norm_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print("original array:", arr)
print("normalized array:", norm_arr)


original array: [10 20 30 40 50]
normalized array: [0.   0.25 0.5  0.75 1.  ]


## Advanced

In [113]:
# •	Implement z-score normalization manually using NumPy.

In [115]:
arr = np.array([10, 20, 30, 40, 50])

mean = np.mean(arr)

std = np.std(arr)

z_score_normalized = (arr - mean) / std

print("original array:", arr)
print("mean:", mean)
print("std dev:", std)
print("z-score normalized array:", z_score_normalized)


original array: [10 20 30 40 50]
mean: 30.0
std dev: 14.142135623730951
z-score normalized array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [117]:
#•	Compute pairwise Euclidean distance between rows of a 2D array.