## Basic

In [2]:
# Problem 1: Create a 1D, 2D, and 3D NumPy array. Print the arrays and their shapes

In [4]:
import numpy as np

In [12]:
a=np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [14]:
b=np.array([[1,2,3,4],[6,5,4,3]])
print(b)
print(b.shape)

[[1 2 3 4]
 [6 5 4 3]]
(2, 4)


In [24]:
c=np.array([
    [[1,2,3,4],[6,5,4,3]],
    [[1,2,3,4],[6,5,4,3]]
           
])
print(c)
print(c.shape)

[[[1 2 3 4]
  [6 5 4 3]]

 [[1 2 3 4]
  [6 5 4 3]]]
(2, 2, 4)


In [26]:
#•	Create an array of numbers from 0 to 20 with step size 2.

In [32]:
a=np.arange(0,21,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [34]:
#•	Slice the above array to get only even numbers.

In [44]:
a=np.arange(0,21)
print(a[::2])

[ 0  2  4  6  8 10 12 14 16 18 20]


In [46]:
#•	Create a 3x3 matrix and extract the 2nd row and 3rd column.

In [76]:
c = np.array([
    [1, 2, 3], 
    [6, 5, 4], 
    [1, 2, 3]
])

print(c.shape)

print("2nd row:", c[1, :])
print("3rd cols:", c[:,2])




(3, 3)
2nd row: [6 5 4]
3rd cols: [3 4 3]
