In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [18]:
b = np.array([[1.0,2.9,3.6],[3.3,5.6,6.7]])
print(b)

[[1.  2.9 3.6]
 [3.3 5.6 6.7]]


In [20]:
#get dimension
a.ndim

1

In [22]:
#get shape
a.shape

(3,)

In [24]:
b.shape

(2, 3)

In [26]:
b.ndim

2

In [30]:
#get type
a.dtype

dtype('int32')

In [36]:
a.dtype

dtype('int32')

In [38]:
a.dtype

dtype('int32')

In [40]:
a.dtype

dtype('int32')

In [42]:
print(a.dtype)

int32


In [44]:
a = np.array([1,2,3], dtype='int16')
print(a)
print (a.dtype)

[1 2 3]
int16


In [46]:
#get size
a.itemsize

2

In [48]:
b.itemsize

8

In [50]:
a = np.array([1,2,3], dtype='int32')
print(a)
print (a.dtype)
print(a.itemsize)

[1 2 3]
int32
4


In [52]:
b = np.array([[1.0,2.9,3.6],[3.3,5.6,6.7]],dtype='int16')
print(b)
print (b.dtype)
print(b.itemsize)

[[1 2 3]
 [3 5 6]]
int16
2


In [54]:
a.size*a.itemsize #a.nbytes 

12

In [56]:
a.size

3

In [58]:
a.nbytes

12

In [60]:
b.nbytes

12